name: 'List Files Action'
description: 'List all matching files in specific path.'
author: "Mirko Felice"

inputs:
  repo:
    description: "Repository name where to search files"
    required: true
  ref:
    description: "Branch or tag to checkout"
    default: "master"
    required: false
  path:
    description: "Path where searching files"
    required: true
  ext:
    description: "File extension to match"
    required: true
outputs:
  paths:
    value: ${{ steps.py.outputs.paths }}
    description: "List of all matching files"

runs:
  using: composite
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v3.0.2
      with:
        repository: ${{ inputs.repo }}
        ref: ${{ inputs.ref }}
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.7'
    - shell: bash
      id: py
      name: Execute Python
      env:
        INPUT_PATH: ${{ inputs.path }}
        INPUT_EXT: ${{ inputs.ext }}
      run: python ${{ github.action_path }}/main.py

branding:
  icon: file
  color: gray-dark
