name: Test

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - 'master'
    paths-ignore:
      - 'CHANGELOG.md'
  pull_request:
  workflow_dispatch:

jobs:
  list-files:
    runs-on: ubuntu-latest
    outputs:
      paths: ${{ steps.list-files.outputs.paths }}
    steps:
      - name: List Files
        id: list-files
        uses: mirko-felice/list-files-action@master
        with:
          repo: ${{ github.repository }}
          ref: ${{ github.ref }}
          path: "."
          ext: ".yml"
  Test:
    needs: list-files
    strategy:
      matrix:
        paths: ${{ fromJson(needs.list-files.outputs.paths) }}
    runs-on: ubuntu-latest
    steps:
      - name: Output results
        run: |
          echo ${{ matrix.paths }}
  Release:
    if: github.ref_name == 'master'
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.5.3
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Import GPG
        uses: crazy-max/ghaction-import-gpg@v5.3.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Publish Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_COMMITTER_NAME: Mirko Felice
          GIT_COMMITTER_EMAIL: mirko.felice@studio.unibo.it
          GIT_AUTHOR_NAME: Mirko Felice
          GIT_AUTHOR_EMAIL: mirko.felice@studio.unibo.it
        run: |
          npm install
          npx semantic-release